#!/usr/bin/env bash
set -e
command=$1

if [[ ! -f "$HOME/.vim/janus/vim/core/pathogen/autoload/pathogen.vim" ]]; then
  vpm-pathogen-instructions
  exit 1
fi

case "$command" in
  ""|"-h"|"--help")
    vpm-help
    ;;
  "-v"|"--version")
    vpm-version
    ;;
  *)
    if command -v "vpm-$command" > /dev/null; then
      shift && exec "vpm-$command" "$@"
    else
      vpm-insert "$@"
    fi
    ;;
esac
